# frozen_string_literal: true

require 'bundler/gem_tasks'
require 'rspec/core/rake_task'
require 'cucumber/rake/task'
require 'rubocop/rake_task'
require 'reek/rake/task'

RSpec::Core::RakeTask.new(:spec)
Cucumber::Rake::Task.new(:features)
RuboCop::RakeTask.new(:rubocop) do |t|
  t.options = ['--auto-correct']
end
Reek::Rake::Task.new(:reek)

task default: %i[spec features rubocop]
